{% set name = "sagemaker-mxnet-serving-container" %}
{% set version = "1.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/aws/{{ name }}/archive/v{{ version }}.zip
  sha256: 07093de3565a85191b606f15fb3f486e578eeb6ee1a8de67e100cb87a455d771

build:
  noarch: python
  number: 0
  entry_points:
    - serve=sagemaker_mxnet_serving_container.serving:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - retrying

test:
  imports:
    - sagemaker_mxnet_serving_container

about:
  home: https://github.com/aws/sagemaker-mxnet-containers
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Open source library for creating MXNet containers to run on Amazon SageMaker.
  dev_url: https://github.com/aws/sagemaker-mxnet-serving-container

extra:
  recipe-maintainers:
    - mxr-conda
    - oblute
    - benhuff
    - rluria14
